name: Synthetics Run
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '* */6 * * *'
jobs:
  e-commerce-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'e-commerce'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22.3'
      - run: npm install
      - run: "SYNTHETICS_JUNIT_FILE='junit-synthetics.xml' npx @elastic/synthetics . --reporter=junit"
        continue-on-error: true
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/junit-*.xml'
          fail_on_failure: true
          require_tests: true
  todos_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'todos/synthetics-tests'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.22.3'
      - run: npm install
      - run: "SYNTHETICS_JUNIT_FILE='junit-synthetics.xml' npx @elastic/synthetics . --reporter=junit --suite-params='{\"url\": \"https://elastic.github.io/synthetics-demo/\"} '"
        continue-on-error: true
      - name: Publish JUnit Test Report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/junit-*.xml'
          fail_on_failure: true
          require_tests: true
